"""RED contracts for connect cards generated by README section rendering."""

from __future__ import annotations

import re
from pathlib import Path

from scripts.config import ReadmeSectionsSettings, ReadmeSocialLink, ReadmeSvgSettings
from scripts.readme_sections import ReadmeSectionGenerator


def _render_connect_card_output(tmp_path: Path) -> tuple[str, str]:
    settings = ReadmeSectionsSettings(
        svg=ReadmeSvgSettings(
            enabled=True,
            output_dir=str(tmp_path / "svg"),
            top_contact=True,
            featured_projects=False,
            blog_posts=False,
        ),
        social_links=[
            ReadmeSocialLink(
                label="GitHub",
                url="https://github.com/wyattowalsh",
                color="181717",
                logo="github",
            )
        ],
    )
    generator = ReadmeSectionGenerator(settings=settings)

    html = generator._render_top_badges()
    card_svgs = sorted((tmp_path / "svg").glob("top-contact-card-*.svg"))
    assert len(card_svgs) == 1
    svg = card_svgs[0].read_text(encoding="utf-8")
    return html, svg


def test_connect_cards_keep_transparent_headerless_icon_first_and_noise_free_copy(
    tmp_path: Path,
) -> None:
    html, svg = _render_connect_card_output(tmp_path)

    assert "top-contact-card-01-github.svg" in html
    assert '<text class="title"' not in svg
    assert '<rect width="100%" height="100%"' not in svg
    assert 'class="card-icon-image"' in svg
    assert svg.index('class="card-icon-image"') < svg.index('class="card-title"')
    visible_lines = re.findall(r'<text class="card-line"[^>]*>([^<]+)</text>', svg)
    assert all("@" not in line and "://" not in line for line in visible_lines)
    assert all("open-profile" not in line.lower() for line in visible_lines)
    assert 'href="https://github.com/wyattowalsh"' in svg


def test_connect_cards_require_future_modern_polish_hooks_red(tmp_path: Path) -> None:
    _, svg = _render_connect_card_output(tmp_path)

    expected_hooks = (
        'class="connect-card-shell"',
        'class="connect-brand-lockup"',
        "--connect-accent-glow",
        'data-connect-variant="gh-card"',
    )
    missing = [hook for hook in expected_hooks if hook not in svg]
    assert not missing, (
        "Expected gh-card-inspired modern polish hooks in connect SVG output; "
        f"missing: {missing}"
    )
