"""Generate deterministic language and topic indexes from GitHub stars.

The GitHub GraphQL response is treated as untrusted input. Both Markdown files
are rendered from one pagination pass and staged completely before either
destination is replaced. If the second replacement fails, the first output is
restored to its exact pre-call bytes and mode unless an external writer changed
it, in which case rollback fails closed without overwriting that newer content.
"""

from __future__ import annotations

import argparse
import fcntl
import hashlib
import hmac
import html
import math
import os
import re
import stat
import tempfile
import time
from collections import defaultdict
from collections.abc import Iterator, Mapping, Sequence
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import urlparse

from ._github_http import _graphql
from .utils import get_logger

logger = get_logger(module=__name__)

DEFAULT_TOPIC_THRESHOLD = 500
DESCRIPTION_LENGTH_LIMIT = 200
_MAX_GRAPHQL_PAGES = 1_000
_MAX_TRANSIENT_RETRIES = 3
_INITIAL_RETRY_DELAY_SECONDS = 1.0
_SECONDARY_RATE_LIMIT_FALLBACK_SECONDS = 60.0
_FETCH_DEADLINE_SECONDS = 24 * 60.0
_RETRYABLE_HTTP_STATUSES = frozenset({429, 502, 503, 504})
_LANGUAGE_FALLBACK = "Others"
_TOPIC_FALLBACK = "others"
# GitHub still serves legacy account logins that end in a hyphen even though
# newly created usernames follow the stricter DNS-like form. Treat GraphQL's
# printable login scalar as authoritative while retaining the documented
# 1..39 character/path-safe alphabet and rejecting leading punctuation.
_OWNER_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9-]{0,38}$")
_REPOSITORY_RE = re.compile(r"^[A-Za-z0-9._-]{1,100}$")
_TOPIC_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,49}$")

_STARRED_REPOSITORIES_QUERY = """
query StarredRepositories($owner: String!, $after: String) {
  user(login: $owner) {
    starredRepositories(
      first: 100
      after: $after
      orderBy: {field: STARRED_AT, direction: DESC}
    ) {
      totalCount
      nodes {
        id
        nameWithOwner
        description
        url
        isPrivate
        languages(first: 1, orderBy: {field: SIZE, direction: DESC}) {
          edges {
            node {
              name
            }
          }
        }
        repositoryTopics(first: 100) {
          nodes {
            topic {
              name
              stargazerCount
            }
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
""".strip()

_MARKDOWN_HEADER = "\n".join(
    (
        "<!--lint disable awesome-contributing awesome-license awesome-list-item "
        "match-punctuation no-repeat-punctuation no-undefined-references "
        "awesome-spell-check-->",
        "# Awesome Stars "
        "[![Awesome](https://awesome.re/badge.svg)]"
        "(https://github.com/sindresorhus/awesome)",
        "",
        "> A curated list of my GitHub stars, generated by the repository-owned "
        "`scripts.starred_lists` module.",
        "",
        "## Contents",
    )
)


class StarredListsError(RuntimeError):
    """A fetch, validation, rendering, or publication contract failed."""


@dataclass(frozen=True, slots=True)
class _Topic:
    name: str
    stargazer_count: int


@dataclass(frozen=True, slots=True)
class _Repository:
    node_id: str
    name_with_owner: str
    description: str
    url: str
    is_private: bool
    primary_language: str | None
    topics: tuple[_Topic, ...]


@dataclass(frozen=True, slots=True)
class _OutputSnapshot:
    existed: bool
    payload: bytes | None
    mode: int | None
    revision: tuple[int, int, int, int] | None
    payload_sha256: bytes | None


@dataclass(frozen=True, slots=True)
class _PublishedOutput:
    revision: tuple[int, int, int, int]
    payload_sha256: bytes


class _ConcurrentOutputMutationError(StarredListsError):
    """A non-cooperating writer changed an output during publication."""


class _GraphQLRateLimitError(RuntimeError):
    """An HTTP-200 GraphQL response contained only rate-limit errors."""

    def __init__(self, response_headers: Mapping[str, str]) -> None:
        super().__init__("GitHub GraphQL rate limit response")
        self.response_headers = dict(response_headers)


def _required_mapping(value: Any, *, label: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise StarredListsError(f"GitHub GraphQL field is not an object: {label}")
    return value


def _required_sequence(value: Any, *, label: str) -> Sequence[Any]:
    if isinstance(value, (str, bytes)) or not isinstance(value, Sequence):
        raise StarredListsError(f"GitHub GraphQL field is not a list: {label}")
    return value


def _required_string(value: Any, *, label: str) -> str:
    if not isinstance(value, str) or not value or not value.isprintable():
        raise StarredListsError(f"GitHub GraphQL field is not a valid string: {label}")
    return value


def _validate_owner(owner: str) -> str:
    normalized = owner.strip()
    if not _OWNER_RE.fullmatch(normalized):
        raise StarredListsError("GitHub owner has an invalid format")
    return normalized


def _validate_repository_url(url: str, *, name_with_owner: str) -> str:
    parsed = urlparse(url)
    if (
        parsed.scheme != "https"
        or parsed.hostname != "github.com"
        or parsed.username is not None
        or parsed.password is not None
        or parsed.port is not None
        or parsed.params
        or parsed.query
        or parsed.fragment
        or parsed.path.strip("/").casefold() != name_with_owner.casefold()
    ):
        raise StarredListsError("GitHub repository URL failed its safety contract")
    return url


def _parse_primary_language(raw: Any, *, label: str) -> str | None:
    languages = _required_mapping(raw, label=label)
    edges = _required_sequence(languages.get("edges"), label=f"{label}.edges")
    if len(edges) > 1:
        raise StarredListsError("Primary-language query returned multiple edges")
    if not edges:
        return None
    edge = _required_mapping(edges[0], label=f"{label}.edges[0]")
    node = _required_mapping(edge.get("node"), label=f"{label}.edges[0].node")
    language = _required_string(node.get("name"), label=f"{label}.name").strip()
    if not language or len(language) > 100 or any(char in "\r\n" for char in language):
        raise StarredListsError("Primary language failed its text contract")
    return language


def _parse_topics(raw: Any, *, label: str) -> tuple[_Topic, ...]:
    repository_topics = _required_mapping(raw, label=label)
    nodes = _required_sequence(repository_topics.get("nodes"), label=f"{label}.nodes")
    topics: list[_Topic] = []
    seen: set[str] = set()
    for index, raw_node in enumerate(nodes):
        wrapper = _required_mapping(raw_node, label=f"{label}.nodes[{index}]")
        topic = _required_mapping(
            wrapper.get("topic"), label=f"{label}.nodes[{index}].topic"
        )
        name = _required_string(
            topic.get("name"), label=f"{label}.nodes[{index}].topic.name"
        )
        if not _TOPIC_RE.fullmatch(name):
            raise StarredListsError("Repository topic failed its text contract")
        count = topic.get("stargazerCount")
        if type(count) is not int or count < 0:
            raise StarredListsError("Repository topic has an invalid stargazer count")
        if name in seen:
            raise StarredListsError("Repository topic list contains a duplicate")
        seen.add(name)
        topics.append(_Topic(name=name, stargazer_count=count))
    return tuple(topics)


def _parse_repository(raw: Any, *, page: int, index: int) -> _Repository:
    label = f"page[{page}].nodes[{index}]"
    node = _required_mapping(raw, label=label)
    node_id = _required_string(node.get("id"), label=f"{label}.id")
    name_with_owner = _required_string(
        node.get("nameWithOwner"), label=f"{label}.nameWithOwner"
    )
    name_parts = name_with_owner.split("/")
    if (
        len(name_parts) != 2
        or not _OWNER_RE.fullmatch(name_parts[0])
        or not _REPOSITORY_RE.fullmatch(name_parts[1])
    ):
        raise StarredListsError("GitHub repository name has an invalid format")
    url = _validate_repository_url(
        _required_string(node.get("url"), label=f"{label}.url"),
        name_with_owner=name_with_owner,
    )
    is_private = node.get("isPrivate")
    if type(is_private) is not bool:
        raise StarredListsError("GitHub repository privacy flag is invalid")
    description = node.get("description")
    if description is None:
        description = ""
    if not isinstance(description, str):
        raise StarredListsError("GitHub repository description is invalid")
    return _Repository(
        node_id=node_id,
        name_with_owner=name_with_owner,
        description=description,
        url=url,
        is_private=is_private,
        primary_language=_parse_primary_language(
            node.get("languages"), label=f"{label}.languages"
        ),
        topics=_parse_topics(
            node.get("repositoryTopics"), label=f"{label}.repositoryTopics"
        ),
    )


def _response_headers(response: Mapping[str, Any]) -> Mapping[str, str]:
    headers = getattr(response, "response_headers", None)
    return headers if isinstance(headers, Mapping) else {}


def _header_value(headers: Any, name: str) -> str | None:
    getter = getattr(headers, "get", None)
    if not callable(getter):
        return None
    value = getter(name)
    if value is None:
        value = getter(name.casefold())
    if value is None:
        return None
    normalized = str(value).strip()
    return normalized or None


def _non_negative_header_integer(headers: Any, name: str) -> int | None:
    raw = _header_value(headers, name)
    if raw is None or not raw.isascii() or not raw.isdigit() or len(raw) > 19:
        return None
    value = int(raw)
    return value if value <= (2**63 - 1) else None


def _rate_limit_delay_from_headers(headers: Any) -> float | None:
    retry_after = _non_negative_header_integer(headers, "Retry-After")
    if retry_after is not None:
        return float(max(1, retry_after))

    if _header_value(headers, "X-RateLimit-Remaining") != "0":
        return None
    reset_at = _non_negative_header_integer(headers, "X-RateLimit-Reset")
    if reset_at is None:
        return None
    return float(max(1, math.ceil(reset_at - time.time())))


def _only_rate_limited_graphql_errors(response: Mapping[str, Any]) -> bool:
    errors = response.get("errors")
    return (
        isinstance(errors, list)
        and bool(errors)
        and all(
            isinstance(error, Mapping)
            and str(error.get("type") or "").upper() == "RATE_LIMITED"
            for error in errors
        )
    )


def _retry_delay_for_graphql_error(exc: Exception, *, retries: int) -> float | None:
    fallback = _INITIAL_RETRY_DELAY_SECONDS * (2**retries)
    if isinstance(exc, _GraphQLRateLimitError):
        return (
            _rate_limit_delay_from_headers(exc.response_headers)
            or _SECONDARY_RATE_LIMIT_FALLBACK_SECONDS
        )
    if isinstance(exc, HTTPError):
        header_delay = _rate_limit_delay_from_headers(exc.headers)
        if exc.code == 403:
            return header_delay
        if exc.code == 429 and header_delay is not None:
            return header_delay
        return fallback if exc.code in _RETRYABLE_HTTP_STATUSES else None
    if isinstance(exc, (URLError, TimeoutError)):
        return fallback
    return None


def _is_retryable_graphql_error(exc: Exception) -> bool:
    return _retry_delay_for_graphql_error(exc, retries=0) is not None


def _graphql_with_transient_retries(
    owner: str,
    token: str,
    *,
    after: str | None,
    page_number: int,
    deadline: float,
) -> Mapping[str, Any]:
    retries = 0
    while True:
        if time.monotonic() >= deadline:
            raise TimeoutError("Starred-repository fetch deadline exceeded")
        try:
            response = _graphql(
                _STARRED_REPOSITORIES_QUERY,
                token,
                variables={"owner": owner, "after": after},
            )
            if _only_rate_limited_graphql_errors(response):
                raise _GraphQLRateLimitError(_response_headers(response))
            return response
        except Exception as exc:
            delay = _retry_delay_for_graphql_error(exc, retries=retries)
            status = exc.code if isinstance(exc, HTTPError) else None
            if isinstance(exc, HTTPError):
                exc.close()
            if delay is None or retries >= _MAX_TRANSIENT_RETRIES:
                raise
            if time.monotonic() + delay >= deadline:
                raise
            retries += 1
            logger.info(
                "Transient GitHub GraphQL failure; retrying page={} "
                "retry={}/{} delay_seconds={} error_type={} status={}",
                page_number,
                retries,
                _MAX_TRANSIENT_RETRIES,
                delay,
                type(exc).__name__,
                status,
            )
            time.sleep(delay)


def fetch_starred_repositories(
    owner: str,
    token: str,
) -> tuple[_Repository, ...]:
    """Fetch and strictly validate one owner's complete starred-repository set."""
    owner = _validate_owner(owner)
    if not token or not token.strip():
        raise StarredListsError("GITHUB_TOKEN is required")

    repositories: list[_Repository] = []
    seen_node_ids: set[str] = set()
    seen_names: set[str] = set()
    seen_cursors: set[str] = set()
    after: str | None = None
    expected_total: int | None = None
    deadline = time.monotonic() + _FETCH_DEADLINE_SECONDS

    for page_number in range(1, _MAX_GRAPHQL_PAGES + 1):
        try:
            response = _graphql_with_transient_retries(
                owner,
                token,
                after=after,
                page_number=page_number,
                deadline=deadline,
            )
        except Exception as exc:
            raise StarredListsError("GitHub GraphQL request failed") from exc

        root = _required_mapping(response, label="response")
        if root.get("errors"):
            raise StarredListsError("GitHub GraphQL response contained errors")
        data = _required_mapping(root.get("data"), label="data")
        user = _required_mapping(data.get("user"), label="data.user")
        connection = _required_mapping(
            user.get("starredRepositories"), label="data.user.starredRepositories"
        )
        total_count = connection.get("totalCount")
        if type(total_count) is not int or total_count < 0:
            raise StarredListsError("Starred-repository totalCount is invalid")
        if expected_total is None:
            expected_total = total_count
        elif total_count != expected_total:
            raise StarredListsError(
                "Starred-repository totalCount changed during pagination"
            )

        raw_nodes = _required_sequence(
            connection.get("nodes"), label="data.user.starredRepositories.nodes"
        )
        for index, raw_node in enumerate(raw_nodes):
            repository = _parse_repository(
                raw_node,
                page=page_number,
                index=index,
            )
            folded_name = repository.name_with_owner.casefold()
            if repository.node_id in seen_node_ids or folded_name in seen_names:
                raise StarredListsError(
                    "Starred-repository pagination returned a duplicate"
                )
            seen_node_ids.add(repository.node_id)
            seen_names.add(folded_name)
            repositories.append(repository)

        page_info = _required_mapping(
            connection.get("pageInfo"),
            label="data.user.starredRepositories.pageInfo",
        )
        has_next_page = page_info.get("hasNextPage")
        if type(has_next_page) is not bool:
            raise StarredListsError("Pagination hasNextPage is invalid")
        end_cursor = page_info.get("endCursor")
        if not has_next_page:
            if len(repositories) != expected_total:
                raise StarredListsError(
                    "Starred-repository pagination count does not match totalCount"
                )
            return tuple(repositories)
        if not raw_nodes:
            raise StarredListsError("Pagination advertised another page without nodes")
        if (
            not isinstance(end_cursor, str)
            or not end_cursor
            or len(end_cursor) > 4_096
            or not end_cursor.isprintable()
            or end_cursor in seen_cursors
        ):
            raise StarredListsError("Pagination cursor is invalid or cyclic")
        seen_cursors.add(end_cursor)
        after = end_cursor

    raise StarredListsError("Starred-repository pagination exceeded its page limit")


def _sanitize_description(description: str) -> str:
    normalized = " ".join(description.split())[:DESCRIPTION_LENGTH_LIMIT].rstrip()
    escaped = html.escape(normalized, quote=True)
    for character, entity in (
        ("\\", "&#92;"),
        ("`", "&#96;"),
        ("*", "&#42;"),
        ("_", "&#95;"),
        ("[", "&#91;"),
        ("]", "&#93;"),
    ):
        escaped = escaped.replace(character, entity)
    return escaped


def _category_sort_key(value: str) -> tuple[str, str]:
    return value.casefold(), value


def _repository_sort_key(repository: _Repository) -> tuple[str, str, str]:
    return (
        repository.name_with_owner.casefold(),
        repository.name_with_owner,
        repository.url,
    )


def _anchor_base(category: str) -> str:
    normalized = category.casefold().replace(" ", "-")
    normalized = re.sub(r"[^\w-]", "", normalized)
    normalized = re.sub(r"-+", "-", normalized).strip("-")
    return normalized or "category"


def _category_anchors(categories: Sequence[str]) -> dict[str, str]:
    counts: defaultdict[str, int] = defaultdict(int)
    anchors: dict[str, str] = {}
    for category in categories:
        base = _anchor_base(category)
        suffix = counts[base]
        counts[base] += 1
        anchors[category] = base if suffix == 0 else f"{base}-{suffix}"
    return anchors


def _render_markdown(
    owner: str,
    categories: Mapping[str, Sequence[_Repository]],
) -> str:
    sorted_categories = sorted(categories, key=_category_sort_key)
    anchors = _category_anchors(sorted_categories)
    lines = [_MARKDOWN_HEADER.rstrip(), ""]

    if sorted_categories:
        for category in sorted_categories:
            display = html.escape(category, quote=True)
            lines.append(f"- [{display}](#{anchors[category]})")
    else:
        lines.append("_No public starred repositories._")

    for category in sorted_categories:
        display_category = html.escape(category, quote=True)
        lines.extend(("", f"## {display_category}", ""))
        for repository in sorted(categories[category], key=_repository_sort_key):
            display_name = html.escape(repository.name_with_owner, quote=True)
            description = _sanitize_description(repository.description)
            line = f"- [{display_name}]({repository.url})"
            if description:
                line += f" - {description}"
            lines.append(line)

    safe_owner = html.escape(owner, quote=True)
    lines.extend(
        (
            "",
            "## License",
            "",
            "[![CC0](https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg)](https://creativecommons.org/publicdomain/zero/1.0/)",
            "",
            f"To the extent possible under law, [{safe_owner}]"
            f"(https://github.com/{owner}) has waived all copyright and related "
            "or neighboring rights to this work.",
            "",
        )
    )
    return "\n".join(lines)


def render_starred_lists(
    owner: str,
    repositories: Sequence[_Repository],
    *,
    topic_threshold: int = DEFAULT_TOPIC_THRESHOLD,
    include_private: bool = False,
) -> tuple[str, str]:
    """Render language and topic Markdown from one validated repository set."""
    owner = _validate_owner(owner)
    if type(topic_threshold) is not int or topic_threshold < 0:
        raise StarredListsError("Topic threshold must be a non-negative integer")

    language_categories: defaultdict[str, list[_Repository]] = defaultdict(list)
    topic_categories: defaultdict[str, list[_Repository]] = defaultdict(list)
    for repository in repositories:
        if repository.is_private and not include_private:
            continue
        language_categories[repository.primary_language or _LANGUAGE_FALLBACK].append(
            repository
        )
        selected_topics = [
            topic.name
            for topic in repository.topics
            if topic.stargazer_count > topic_threshold
        ]
        for topic in selected_topics or [_TOPIC_FALLBACK]:
            topic_categories[topic].append(repository)

    return (
        _render_markdown(owner, language_categories),
        _render_markdown(owner, topic_categories),
    )


def _output_revision(path: Path) -> tuple[int, int, int, int] | None:
    try:
        status = path.lstat()
    except FileNotFoundError:
        return None
    if not stat.S_ISREG(status.st_mode):
        raise StarredListsError("Starred-list output must be a regular file")
    return status.st_dev, status.st_ino, status.st_size, status.st_mtime_ns


def _snapshot_output(path: Path) -> _OutputSnapshot:
    revision = _output_revision(path)
    if revision is None:
        return _OutputSnapshot(False, None, None, None, None)
    status = path.lstat()
    payload = path.read_bytes()
    if _output_revision(path) != revision:
        raise StarredListsError("Starred-list output changed while it was read")
    return _OutputSnapshot(
        existed=True,
        payload=payload,
        mode=stat.S_IMODE(status.st_mode),
        revision=revision,
        payload_sha256=hashlib.sha256(payload).digest(),
    )


def _stage_payload(path: Path, payload: bytes, *, mode: int) -> Path:
    descriptor, stage_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".publish.tmp",
        dir=path.parent,
    )
    stage_path = Path(stage_name)
    try:
        with os.fdopen(descriptor, "wb") as file_obj:
            file_obj.write(payload)
            file_obj.flush()
            os.fsync(file_obj.fileno())
        os.chmod(stage_path, mode)
        return stage_path
    except BaseException:
        stage_path.unlink(missing_ok=True)
        raise


def _output_matches_revision_and_digest(
    path: Path,
    *,
    revision: tuple[int, int, int, int],
    payload_sha256: bytes,
) -> bool:
    try:
        if _output_revision(path) != revision:
            return False
        payload = path.read_bytes()
        if _output_revision(path) != revision:
            return False
    except (OSError, StarredListsError):
        return False
    return hmac.compare_digest(
        hashlib.sha256(payload).digest(),
        payload_sha256,
    )


def _snapshot_output_matches(path: Path, snapshot: _OutputSnapshot) -> bool:
    """Return whether *path* still has the exact snapshotted identity and bytes."""
    if not snapshot.existed:
        try:
            return _output_revision(path) is None
        except (OSError, StarredListsError):
            return False
    if snapshot.revision is None or snapshot.payload_sha256 is None:
        return False
    return _output_matches_revision_and_digest(
        path,
        revision=snapshot.revision,
        payload_sha256=snapshot.payload_sha256,
    )


def _published_output_matches(path: Path, expected: _PublishedOutput) -> bool:
    """Return whether *path* still contains this invocation's publication."""
    return _output_matches_revision_and_digest(
        path,
        revision=expected.revision,
        payload_sha256=expected.payload_sha256,
    )


@contextmanager
def _publication_locks(outputs: Sequence[Path]) -> Iterator[None]:
    """Serialize cooperating publishers through stable parent-directory locks.

    Directory descriptors avoid repository lock artifacts and stay attached to
    stable inodes even when outputs are atomically replaced. Distinct parents
    are locked in path order so overlapping two-directory publications cannot
    deadlock.
    """
    parents = sorted(
        {output.parent.resolve() for output in outputs},
        key=lambda path: os.fspath(path),
    )
    descriptors: list[int] = []
    flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_CLOEXEC", 0)
    try:
        for parent in parents:
            descriptor = os.open(parent, flags)
            try:
                fcntl.flock(descriptor, fcntl.LOCK_EX)
            except BaseException:
                os.close(descriptor)
                raise
            descriptors.append(descriptor)
        yield
    finally:
        for descriptor in reversed(descriptors):
            os.close(descriptor)


def _restore_output(
    path: Path,
    snapshot: _OutputSnapshot,
    published: _PublishedOutput,
) -> None:
    def assert_still_owned() -> None:
        if not _published_output_matches(path, published):
            raise _ConcurrentOutputMutationError(
                "Starred-list output changed before rollback"
            )

    if not snapshot.existed:
        assert_still_owned()
        path.unlink()
        return
    if snapshot.payload is None or snapshot.mode is None:
        raise StarredListsError("Output rollback snapshot is incomplete")
    stage = _stage_payload(path, snapshot.payload, mode=snapshot.mode)
    try:
        assert_still_owned()
        os.replace(stage, path)
    finally:
        stage.unlink(missing_ok=True)


def _transactional_write_pair(
    languages_output: Path,
    languages_markdown: str,
    topics_output: Path,
    topics_markdown: str,
) -> None:
    outputs = (languages_output, topics_output)
    for output in outputs:
        output.parent.mkdir(parents=True, exist_ok=True)
    logical_outputs = tuple(output.parent.resolve() / output.name for output in outputs)
    if logical_outputs[0] == logical_outputs[1]:
        raise StarredListsError("Language and topic outputs must be different files")

    with _publication_locks(logical_outputs):
        snapshots = tuple(_snapshot_output(output) for output in logical_outputs)
        stages: list[Path] = []
        publications: list[_PublishedOutput] = []
        committed: list[int] = []
        try:
            for output, markdown, snapshot in zip(
                logical_outputs,
                (languages_markdown, topics_markdown),
                snapshots,
                strict=True,
            ):
                payload = markdown.encode("utf-8")
                stage = _stage_payload(
                    output,
                    payload,
                    mode=snapshot.mode if snapshot.mode is not None else 0o644,
                )
                stages.append(stage)
                revision = _output_revision(stage)
                if revision is None:
                    raise StarredListsError("Staged starred-list output disappeared")
                publications.append(
                    _PublishedOutput(
                        revision=revision,
                        payload_sha256=hashlib.sha256(payload).digest(),
                    )
                )

            for index, (stage, output, snapshot, publication) in enumerate(
                zip(
                    stages,
                    logical_outputs,
                    snapshots,
                    publications,
                    strict=True,
                )
            ):
                if not _snapshot_output_matches(output, snapshot):
                    raise StarredListsError(
                        "Starred-list output changed before publication"
                    )
                os.replace(stage, output)
                committed.append(index)
                if not _published_output_matches(output, publication):
                    raise _ConcurrentOutputMutationError(
                        "Starred-list output changed during publication"
                    )
        except BaseException as exc:
            rollback_errors: list[BaseException] = []
            for index in reversed(committed):
                try:
                    _restore_output(
                        logical_outputs[index],
                        snapshots[index],
                        publications[index],
                    )
                except BaseException as rollback_exc:
                    rollback_errors.append(rollback_exc)
            if rollback_errors:
                concurrent_mutation = any(
                    isinstance(error, _ConcurrentOutputMutationError)
                    for error in rollback_errors
                )
                detail = (
                    " due to concurrent output mutation" if concurrent_mutation else ""
                )
                raise StarredListsError(
                    "Starred-list publication failed and rollback was incomplete"
                    f"{detail}"
                ) from exc
            raise
        finally:
            for stage in stages:
                stage.unlink(missing_ok=True)


def generate_starred_lists(
    *,
    owner: str,
    token: str,
    languages_output: Path,
    topics_output: Path,
    topic_threshold: int = DEFAULT_TOPIC_THRESHOLD,
    include_private: bool = False,
) -> tuple[Path, Path]:
    """Fetch once, render both list views, and publish them transactionally."""
    repositories = fetch_starred_repositories(owner, token)
    languages_markdown, topics_markdown = render_starred_lists(
        owner,
        repositories,
        topic_threshold=topic_threshold,
        include_private=include_private,
    )
    _transactional_write_pair(
        Path(languages_output),
        languages_markdown,
        Path(topics_output),
        topics_markdown,
    )
    logger.info(
        "Generated starred-list outputs from {} repositories: languages={}, topics={}",
        len(repositories),
        languages_output,
        topics_output,
    )
    return Path(languages_output), Path(topics_output)


def _non_negative_integer(raw: str) -> int:
    try:
        value = int(raw)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("must be an integer") from exc
    if value < 0:
        raise argparse.ArgumentTypeError("must be non-negative")
    return value


def main(argv: Sequence[str] | None = None) -> int:
    """Run the first-party starred-list generator CLI."""
    parser = argparse.ArgumentParser(
        description="Generate language and topic Markdown from GitHub stars."
    )
    parser.add_argument("--owner", required=True, help="GitHub user or organization")
    parser.add_argument(
        "--languages-output",
        required=True,
        type=Path,
        help="Destination for the language-grouped Markdown",
    )
    parser.add_argument(
        "--topics-output",
        required=True,
        type=Path,
        help="Destination for the topic-grouped Markdown",
    )
    parser.add_argument(
        "--topic-threshold",
        type=_non_negative_integer,
        default=DEFAULT_TOPIC_THRESHOLD,
        help=(
            "Include repository topics whose global stargazer count exceeds this value"
        ),
    )
    args = parser.parse_args(argv)

    token = os.environ.get("GITHUB_TOKEN", "")
    if not token.strip():
        logger.error("GITHUB_TOKEN is required for starred-list generation")
        return 2
    try:
        generate_starred_lists(
            owner=args.owner,
            token=token,
            languages_output=args.languages_output,
            topics_output=args.topics_output,
            topic_threshold=args.topic_threshold,
        )
    except (OSError, StarredListsError) as exc:
        logger.error("Starred-list generation failed: {}", exc)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
