name: update awesome-stars
on:
  workflow_dispatch:
  schedule:
  - cron: "30 0 * * *"
jobs:
  awesome-stars:
    name: Update Awesome Stars
    runs-on: ubuntu-latest
    permissions:
      contents: write # For committing the updated .md files
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13 and uv
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'uv'
    - name: Install dependencies
      run: uv pip install .[script-tools]
    - name: Get repository name
      run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
    - name: Update repo category by language
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY: ${{ env.REPOSITORY_NAME }}
        USERNAME: ${{ github.repository_owner }}
      run: starred --username ${USERNAME} --repository ${REPOSITORY} --sort --token ${GITHUB_TOKEN} --message 'chore(data): update awesome-stars languages' --filename ./.github/assets/languages.md
    - name: Update repo category by topic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY: ${{ env.REPOSITORY_NAME }}
        USERNAME: ${{ github.repository_owner }}
      run: starred --username ${USERNAME} --repository ${REPOSITORY} --sort --token ${GITHUB_TOKEN} --message 'chore(data): update awesome-stars topics' --topic --topic_limit 500 --filename ./.github/assets/topics.md
