name: Generate starred projects wordclouds
on:
  workflow_dispatch:
    schedule:
    - cron: "35 0 * * *"
jobs:
  wordclouds:
    name: Generate Word Clouds
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13 and uv
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'uv'
    - name: Install dependencies
      run: uv pip install .[word-clouds]
    - name: Generate wordclouds
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python3 scripts/word_clouds.py
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: update word clouds via GitHub Actions"
        commit_user_name: "github-actions[bot]"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
        commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

