name: Generate starred projects wordclouds
on:
  workflow_dispatch:
    schedule:
    - cron: 35 0 * * *
jobs:
  wordclouds:
    name: Generate wordclouds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/word_cloud_requirements.txt
    - name: Generate wordclouds
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python3 scripts/word_clouds.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated with wordclouds action

